// Applied → career-ops tracker sync, following the pipeline-integrity rules:
// never append to data/applications.md directly; write a TSV to
// batch/tracker-additions/ plus a report in reports/, then run merge-tracker.mjs.
import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { REPO_ROOT, REPORTS_DIR, TRACKER_ADD_DIR, MERGE_TRACKER, RESUME_ROOT } from '../paths.mjs';
import { db, nowIso, addEvent, getJob, latestAnalysis, latestResume, setStatus } from '../db.mjs';

function slug(company) {
  return (
    company
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'company'
  );
}

function today() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function nextReportNum() {
  let max = 0;
  for (const dir of [REPORTS_DIR, TRACKER_ADD_DIR]) {
    let entries = [];
    try {
      entries = fs.readdirSync(dir);
    } catch {
      continue;
    }
    for (const f of entries) {
      const m = f.match(/^(\d+)-/);
      if (m) max = Math.max(max, parseInt(m[1], 10));
    }
  }
  return max + 1;
}

function relPdfPath(resume) {
  if (!resume?.pdf_path || !fs.existsSync(resume.pdf_path)) return null;
  return path.relative(REPO_ROOT, resume.pdf_path);
}

function writeReport(num, date, job, analysis, resume, notes) {
  const s = slug(job.company);
  const file = `${String(num).padStart(3, '0')}-${s}-${date}.md`;
  const pdfRel = relPdfPath(resume);
  const score = analysis ? analysis.score.toFixed(1) : '0.0';
  const pros = (analysis?.pros || []).map((p) => `- ${p}`).join('\n') || '- (not analyzed)';
  const cons = (analysis?.cons || []).map((c) => `- ${c}`).join('\n') || '- (not analyzed)';
  const body = `# Evaluation: ${job.company} — ${job.title}

**Date:** ${date}
**URL:** ${job.url}
**Archetype:** Backend Engineer
**Score:** ${score}/5
**Legitimacy:** Unverified (auto-recorded at apply time)
**PDF:** ${pdfRel || '❌'}
**Verification:** unconfirmed (job-hunter)

---

## Summary

${analysis?.reasoning || 'Recorded by job-hunter without a stored analysis.'}

${analysis?.location_check ? `**Location check:** ${analysis.location_check}\n` : ''}
## Pros

${pros}

## Cons

${cons}

## Notes

${notes || '(none)'}

Auto-generated by job-hunter when the application was marked Applied on ${date}.

## Machine Summary

\`\`\`yaml
company: ${JSON.stringify(job.company)}
role: ${JSON.stringify(job.title)}
score: ${score}
status: Applied
url: ${JSON.stringify(job.url)}
date: ${date}
source: job-hunter
\`\`\`
`;
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  fs.writeFileSync(path.join(REPORTS_DIR, file), body);
  return file;
}

function writeTsv(num, date, job, analysis, resume, reportFile, notes) {
  const clean = (s) => String(s || '').replace(/[\t\n]+/g, ' ').trim();
  const score = analysis ? analysis.score.toFixed(1) : '0.0';
  const pdfEmoji = relPdfPath(resume) ? '✅' : '❌';
  const note = clean(notes || analysis?.reasoning || '').slice(0, 140) || 'Applied via job-hunter';
  // Column order per career-ops contract: status BEFORE score.
  const line = [
    num,
    date,
    clean(job.company),
    clean(job.title),
    'Applied',
    `${score}/5`,
    pdfEmoji,
    `[${num}](reports/${reportFile})`,
    note,
  ].join('\t');
  fs.mkdirSync(TRACKER_ADD_DIR, { recursive: true });
  const tsvPath = path.join(TRACKER_ADD_DIR, `${num}-${slug(job.company)}.tsv`);
  fs.writeFileSync(tsvPath, line + '\n');
  return tsvPath;
}

function runMergeTracker() {
  return new Promise((resolve, reject) => {
    const child = spawn('node', [MERGE_TRACKER], { cwd: REPO_ROOT });
    let out = '';
    let err = '';
    child.stdout.on('data', (d) => (out += d));
    child.stderr.on('data', (d) => (err += d));
    child.on('error', reject);
    child.on('close', (code) =>
      code === 0 ? resolve(out) : reject(new Error(`merge-tracker exited ${code}: ${(err || out).slice(0, 400)}`))
    );
  });
}

/**
 * Mark a job as applied: applications row, status, and (once) tracker sync.
 * Idempotent — re-marking an applied job with a tracker_num does nothing new.
 */
export async function markApplied(jobId, { notes = '', method = 'manual' } = {}) {
  const job = getJob(jobId);
  if (!job) throw new Error(`Job ${jobId} not found`);
  const now = nowIso();
  const existing = db.prepare('SELECT * FROM applications WHERE job_id = ?').get(jobId);
  if (existing) {
    if (notes) {
      const merged = existing.notes ? `${existing.notes}\n${notes}` : notes;
      db.prepare('UPDATE applications SET notes = ?, method = ? WHERE job_id = ?').run(merged, method, jobId);
    }
  } else {
    db.prepare('INSERT INTO applications (job_id, applied_at, method, notes) VALUES (?, ?, ?, ?)').run(
      jobId,
      now,
      method,
      notes
    );
    addEvent(jobId, 'applied', { method });
  }
  if (job.status !== 'applied') setStatus(jobId, 'applied', { method });

  const app = db.prepare('SELECT * FROM applications WHERE job_id = ?').get(jobId);
  if (app.tracker_num) {
    return { application: app, trackerSynced: false, alreadySynced: true };
  }

  // Tracker sync — failures are recorded but do not undo the Applied state.
  let reportFile = null;
  let tsvPath = null;
  try {
    const analysis = latestAnalysis(jobId);
    const resume = latestResume(jobId);
    const date = today();
    const num = nextReportNum();
    reportFile = writeReport(num, date, job, analysis, resume, notes);
    tsvPath = writeTsv(num, date, job, analysis, resume, reportFile, notes);
    await runMergeTracker();
    db.prepare('UPDATE applications SET tracker_num = ?, tracker_synced_at = ? WHERE job_id = ?').run(
      num,
      nowIso(),
      jobId
    );
    addEvent(jobId, 'tracker_synced', { num, reportFile });
    return {
      application: db.prepare('SELECT * FROM applications WHERE job_id = ?').get(jobId),
      trackerSynced: true,
      trackerNum: num,
    };
  } catch (e) {
    // Don't leave orphan report/TSV behind — the retry writes fresh ones.
    try {
      if (reportFile) fs.unlinkSync(path.join(REPORTS_DIR, reportFile));
    } catch {}
    try {
      if (tsvPath) fs.unlinkSync(tsvPath);
    } catch {}
    addEvent(jobId, 'tracker_sync_failed', { error: String(e.message || e).slice(0, 500) });
    return { application: app, trackerSynced: false, error: String(e.message || e) };
  }
}
